version: '3'

services:
  bookings-api:
    image: smarthotels/bookings
    build:
      context: .
      dockerfile: SmartHotel.Services.Bookings/Dockerfile

  hotels-api:
    image: smarthotels/hotels
    build:
      context: .
      dockerfile: SmartHotel.Services.Hotels/Dockerfile

  suggestions-api:
    image: smarthotels/suggestions
    build:
      context: .
      dockerfile: SmartHotel.Services.Suggestions/Dockerfile
    depends_on:
      - sql-data

  configuration-api:
    image: smarthotels/configuration
    build:
      context: .
      dockerfile: SmartHotel.Services.Configuration/Dockerfile

  tasks-api:
    image: smarthotels/tasks
    build:
      context: ./SmartHotel.Services.Tasks
      dockerfile: SmartHotel.Services.Tasks/Dockerfile

  reviews-api:
    image: smarthotels/reviews
    build:
      context: ./SmartHotel.Services.Reviews
      dockerfile: SmartHotel.Services.Reviews/Dockerfile    

  notifications-api:
    image: smarthotels/notifications
    build:
      context: .
      dockerfile: SmartHotel.Services.Notifications/Dockerfile

  discounts-api:
    image: smarthotels/discounts
    build:
      context: .
      dockerfile: SmartHotel.Services.Discount/Dockerfile

  profiles-api:
    image: smarthotels/profiles
    build:
      context: ./SmartHotel.Services.Profiles
      dockerfile: SmartHotel.Services.Profiles/Dockerfile

  sql-data:
    image: microsoft/mssql-server-linux:2017-GA

  tasks-data:
    image: postgres:10.1

  reviews-data:
    image: postgres:10.1
  



